# Generated by Django 5.2 on 2025-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
